routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//All routes are disabled for authentication but if it wasnt then i would have done it this way

//Route::middleware('auth')->group(function () {
    Route::get('/', 'AuthorController@index');
    Route::resource('authors', 'AuthorController');
    Route::resource('books', 'BooksController');
//});
Route::get('home', 'HomeController@index')->name('home');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Author extends Model {

    protected $guarded = [];
    
    public function getBadge() {
        return $this->hasOne(Badge::class, 'id', 'badge_id');
    }

    public function getBooksData() {
        return $this->hasManyThrough(Book::class, AuthorBooks::class,  'author_id', 'id', 'id', 'book_id')->orderBy('books.avg_rating', 'desc');
    }

    public function getBooksMapping() {
        return $this->hasMany(AuthorBooks::class, 'author_id');
    }
}

app/Models/AuthorBooks.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AuthorBooks extends Model
{
    protected $guarded = [];

    public function getAuthorDetails() {
        return $this->belongsTo(Author::class, 'author_id');
    }
}

app/Models/Badge.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Badge extends Model
{
    //
}

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAuthor;
use App\Models\Author;
use App\Models\AuthorBooks;
use App\Models\Badge;
use App\Models\Book;
use Exception;
use Illuminate\Http\Request;

class AuthorController extends Controller {

    public function __construct() {
        //$this->middleware('auth');    
    }

    public function index(Request $request) {
        $authors = $this->getAuthors($request->all());
        return view('authors.list', ['authors' => $authors]);
    }

    private function getAuthors($request) {
        try {
            return Author::with(['getBadge', 'getBooksData'])->where(function ($query) use ($request) {
                if(isset($request['searchTerm'])) 
                    return $query->where('name', 'like', '%'.$request['searchTerm'].'%')
                                ->orWhere('email', 'like', '%'.$request['searchTerm'].'%')
                                ->orWhereHas('getBooksData', function ($q) use ($request) {
                                    return $q->where('name', 'like', '%'.$request['searchTerm'].'%')
                                            ->orWhere('isbn', 'like', '%'.$request['searchTerm'].'%');
                                });
            })->paginate(5);
        } catch(Exception $e) {
            dd($e->getMessage());
            return null;
        }
    }

    public function create() {
        return view('authors.create', ['badges' => Badge::get(), 'books' => Book::get()]);
    }

    public function store(CreateAuthor $request) {
        try {
            $request = $request->validated();
            $author = Author::updateOrCreate(['email' => $request['email']], [
                'email' => $request['email'],
                'name' => $request['name'],
                'badge_id' => $request['badge_id'] 
            ]);
            foreach($request['books'] as $book_id) //Because of lack of time i did this .. i would converted into one single Raw SQL query otherwise
                AuthorBooks::updateOrCreate(['author_id' => $author->id, 'book_id' => $book_id], ['author_id' => $author->id, 'book_id' => $book_id]);
            return redirect()->route('authors.index');
        } catch(Exception $e) {
            dd($e->getMessage().' '.$e->getLine());
        }
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BooksController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/authors/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form action="{{route('authors.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>Name : </td>
                                    <td>
                                        <input type="text" name="name" class="form-control" required>
                                        @error('name')
                                            <span style="color:red !important">{{$message}}</span>    
                                        @enderror
                                    </td>
                                </tr>
                                <tr>
                                    <td>Email : </td>
                                    <td>
                                        <input type="email" name="email" class="form-control" required>
                                        @error('email')
                                            <span style="color:red !important">{{$message}}</span>    
                                        @enderror
                                    </td>
                                </tr>
                                <tr>
                                    <td>Badge :</td>
                                    <td>
                                        <select name="badge_id" class="form-control" required>
                                            <option value="">-- SELECT --</option>
                                            @foreach($badges as $badge)
                                                <option value="{{$badge->id}}">{{$badge->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('badge_id')
                                            <span style="color:red !important">{{$message}}</span>    
                                        @enderror
                                    </td>
                                </tr>
                                <tr>
                                    <td>Books Published :</td>
                                    <td>
                                        <select multiple name="books[]" class="form-control">
                                            @foreach ($books as $book)
                                                <option value="{{$book->id}}">{{$book->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('books')
                                            <span style="color:red !important">{{$message}}</span>    
                                        @enderror
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><input type="submit" class="btn btn-md btn-success" value="CREATE"></td>
                                </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/authors/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="text-center">
        <div class="container mb-1 mt-1">
        <form action="{{route('authors.index')}}" method="GET">
            <input type="text" placeholder="Search By Any Keyword Here..." class="form-control" name="searchTerm">
            <input type="submit" class="btn btn-md btn-success">
        </form>
        </div>
        <a href="{{route('authors.create')}}" class="btn btn-md btn-success">Create New Author</a>
        @if($authors !== null && $authors->count() > 0)
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Badge</th>
                    <th>Books Count</th>
                    <th>Books List</th>
                </thead> 
                <tbody>
                    @foreach($authors as $author)
                    <tr>
                        <td>{{$author->name}}</td>
                        <td>{{$author->email}}</td>
                        <td>{{$author->getBadge->name}}</td>
                        <td>{{$author->getBooksData->count()}}</td>
                        <td>{!! implode(', <br>',$author->getBooksData->pluck('name')->toArray()) !!}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{$authors->links()}}
        @else
        <div class="mt-1">
            <h5>No Authors Found !! Please create one !!</h5>
        </div>
        @endif
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="">
            <div class="content">
                <div class="title m-b-md">
                    Voyants Task
                </div>
            </div>
        </div>
        <main class="content">
            @yield('content')
        </main>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>